import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";
import { ModeToggle } from "@/components/ModeToggle";

const geistSans: NextFontWithVariable = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono: NextFontWithVariable = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={ `${geistSans.variable} ${geistMono.variable} antialiased p-2 sm:p-4 md:p-6 grid gap-2 sm:gap-4 md:gap-6` }
            >
                <header className="container mx-auto flex justify-between items-center">
                    <h1>Brandify</h1>
                    <ModeToggle />
                </header>
                <div className="container mx-auto grid gap-6">
                    { children }
                </div>
            </body>
        </html>
    );
}
