import React from 'react';

export default function DummyText() {
    return (
        <div className="text-muted-foreground space-y-2">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab iusto non a odio minima. Rem, provident fugiat blanditiis recusandae veniam omnis magni quaerat sed reprehenderit officiis, nihil earum, ducimus enim. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus hic optio ducimus explicabo nobis esse repudiandae eligendi rem doloremque alias. Ipsa sed ratione minima dicta deleniti, facere libero id quod! Quidem, consequatur ullam! Recusandae ab ipsam vel rerum laudantium aspernatur aliquid, magnam harum necessitatibus maiores facere quaerat? Saepe, eius sapiente iure consequuntur sequi quia consectetur libero blanditiis unde et quos? Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos iusto magnam inventore ut expedita, alias amet ducimus dolores doloribus enim quibusdam commodi minima delectus assumenda quos, eos ab, qui explicabo!</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo cupiditate sed ad doloremque laborum temporibus optio fuga quas quis aut expedita dicta error, sit suscipit, beatae, reprehenderit ipsa architecto repellendus. Temporibus ea saepe voluptatibus magni inventore cum at iure numquam veritatis, quam ipsa quae neque? Provident officia ipsam minus reprehenderit totam cupiditate, deserunt magnam, tempore culpa eaque aliquid voluptate fuga? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eius minus libero aliquid atque in saepe ipsum amet, dolorem doloremque eum temporibus, doloribus ducimus nemo ratione officia, rerum esse. Unde, sapiente. Ipsa, magni atque facere tempora numquam, laudantium neque id sed illo architecto perferendis aut sit nostrum inventore quia corrupti quos? Alias, totam ea libero autem nam ab nostrum ipsam facilis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat id molestias laudantium laboriosam illo? Placeat, fugiat dignissimos natus excepturi atque tempore nobis nemo autem quos quae. Eligendi atque commodi illo?</p>
            <p>Similique dolorem aspernatur necessitatibus unde in tenetur dignissimos velit harum labore excepturi sed debitis corporis nisi autem, quo voluptatibus adipisci ea! Iure commodi consequuntur, laborum similique qui a quas sunt! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quasi perspiciatis nostrum saepe aspernatur debitis hic ad illum laborum a rem, ut culpa voluptatibus, iste cumque ea modi totam nobis neque! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Itaque beatae ducimus quam laudantium pariatur reprehenderit a explicabo, debitis recusandae voluptatum voluptatibus consequuntur obcaecati repudiandae dolor qui nam aspernatur sit? Quibusdam? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur, culpa blanditiis. Impedit, consectetur quas. Nisi eveniet tempora, doloribus quia eaque expedita ea molestias commodi vitae labore quas. Saepe, eaque! Aliquam!
            </p>
        </div>
    );
}
